### ISSUE TITLE
SoundCloud plugin doesn't work at all on Self Hosted site

### ISSUE THREAD

**Issue by finalcut** [idno/SoundCloud#3]
I get a "ruh roh" error when attempting to setup the SoundCloud plugin

steps to reproduce:
1. enable soundcloud plugin
2. click on administration -> SoundCloud
3. get error "Ruh Roh" at http://rawlinson.us/admin/soundcloud/

also fails in the same way if I click on settings and then SoundCloud at the url http://rawlinson.us/account/soundcloud/

All SoundCloud files seem to be present in the /root/IdnoPlugins/SoundCloud directory (which I cloned from here).

**Comment by kylewm** [comment]
Probably 1.5 years too late to help @finalcut, but I suspect this was a missing submodule (php-soundcloud)

I got this exception until I ran

`git submodule init`

**Comment by benwerd** [comment]
Sorry for letting this slip through the cracks, @finalcut, and thank you, @kylewm.

We moved to remove submodules from most plugins for this reason (GitHub doesn't work well with them), but it obviously didn't happen here. Will fix.

**Comment by benwerd** [comment]
Fixed.
