### ISSUE TITLE
Ooops! Services_Soundcloud_Invalid_Http_Response_Code_Exception

### ISSUE THREAD

**Issue by benborges** [idno/SoundCloud#4]
Getting this error message when connecting the soundcloud known app to soundcloud. 
- i can see my site connecting to soundcloud fine and my username
- when i click OK on soundcloud i'm sent back to my website and i have this screen : 

http://i.imgur.com/tP47oIf.png

any chance this might be something on my side, like a missing library or something ?

**Comment by trilliums** [comment]
I am getting the same error. I downloaded the most up to date version of php-soundcloud and the error still happens.

**Comment by trilliums** [comment]
I was able to fix this just now by changing my soundcloud callback URL to HTTPS instead of just HTTP. I created the API with an HTTP callback a few months ago and now I don't allow HTTP connections on my site, hence the error. I hope this helps.

**Comment by buzzworkers** [comment]
using : git clone --recursive https://github.com/idno/SoundCloud
 solve the problem i think
