### ISSUE TITLE
Installing Known in a subdirectory breaks this plugin in the menu.

### ISSUE THREAD

**Issue by trwnh** [idno/SoundCloud#6]
Playing around with a Known installation 
currently hosted at trwnh.com/known, 
and from **trwnh.com/known**/account/settings/, 
when I try to click on "Soundcloud" in the menu, 
it leads to **trwnh.com**/account/soundcloud/ 
instead of **trwnh.com/known**/account/soundcloud/ 
and therefore breaks.

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/SoundCloud/issues/6" class="u-in-reply-to"></a>Thanks for the report!

I'll try and put together a quick patch...

**Comment by trwnh** [comment]
I think it's broken both in user and admin settings, but I didn't fully test every single detail about it. I tried manually modifying the menu.tpl.php file or manually loading the correct link, but I can't find a way to make the "connect" button work, either -- clicking it does nothing, and hovering over it just displays the page URL. So there's something else I seem to be missing.

**Comment by trwnh** [comment]
Similar issue: https://github.com/idno/Foursquare/issues/7
